In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('movies.csv')
data_ratings=pd.read_csv('ratings.csv')

In [3]:
movies.head(5)

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
data_ratings.head(5)

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [2]:
user_item=data_ratings.pivot(index='userId',columns='movieId',values='rating').fillna(0)
user_item.head()
//user_item[1,:]=0
//user_item.head()

NameError: name 'data_ratings' is not defined

In [6]:
Res=user_item.as_matrix()
Res
#users_ids = list(user_item.index)
user_matrix_mean=np.mean(Res,axis=1)
user_matrix_mean


array([0.00562541, 0.02923009, 0.02007501, 0.09783808, 0.04312817,
       0.01582837, 0.03364218, 0.04947055, 0.01864108, 0.01875138,
       0.01709685, 0.01853077, 0.02189499, 0.00650783, 0.49161703,
       0.01318112, 0.14990073, 0.01819987, 0.16490183, 0.03557247,
       0.06265167, 0.07947276, 0.29092213, 0.00849327, 0.00893448,
       0.06579528, 0.0097066 , 0.02360468, 0.00694904, 0.41986543,
       0.03171189, 0.01941319, 0.04985661, 0.08118244, 0.00529451,
       0.04147364, 0.01433929, 0.05255901, 0.02592102, 0.02139863,
       0.08487756, 0.03099493, 0.03639974, 0.00926539, 0.00838297,
       0.02128833, 0.01621443, 0.19887492, 0.03783366, 0.01665564,
       0.01356717, 0.02768586, 0.01411869, 0.01842047, 0.01522171,
       0.2081403 , 0.09121994, 0.02746525, 0.02652769, 0.02536951,
       0.05994926, 0.02360468, 0.04020516, 0.00926539, 0.01235385,
       0.02139863, 0.04268696, 0.04919479, 0.03695125, 0.03849548,
       0.01080962, 0.06833223, 0.59921685, 0.02217075, 0.05244

In [7]:
R_demeaned = Res - user_matrix_mean.reshape(-1, 1)
R_demeaned

array([[-0.00562541, -0.00562541, -0.00562541, ..., -0.00562541,
        -0.00562541, -0.00562541],
       [-0.02923009, -0.02923009, -0.02923009, ..., -0.02923009,
        -0.02923009, -0.02923009],
       [-0.02007501, -0.02007501, -0.02007501, ..., -0.02007501,
        -0.02007501, -0.02007501],
       ...,
       [-0.01367748, -0.01367748, -0.01367748, ..., -0.01367748,
        -0.01367748, -0.01367748],
       [ 3.98698434, -0.01301566, -0.01301566, ..., -0.01301566,
        -0.01301566, -0.01301566],
       [ 4.95030885, -0.04969115, -0.04969115, ..., -0.04969115,
        -0.04969115, -0.04969115]])

In [8]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)

In [9]:
sigma.shape
sigma=np.diag(sigma)
#sigma.shape
#Vt.shape
#sigma

In [10]:
all_user_predicted_ratings =np.dot(np.dot(U, sigma),Vt)
all_predicted_ratings_normalize=all_user_predicted_ratings+user_matrix_mean.reshape(-1,1)
all_predicted_ratings_normalize

array([[-5.42390333e-02,  4.51304289e-02, -4.83461757e-03, ...,
        -6.36490827e-03, -6.09765683e-03, -4.81885918e-03],
       [ 4.19835043e-01,  1.40644018e+00, -1.88807492e-01, ...,
         1.04679741e-03, -1.46825089e-03, -6.57708637e-03],
       [ 1.34561891e+00,  2.66504861e-01, -1.19621144e-02, ...,
         1.06114277e-02,  6.79214329e-03, -6.35703450e-03],
       ...,
       [ 7.28688090e-01, -1.35383733e-01,  1.89809902e-01, ...,
         1.57367435e-03, -3.40631718e-04, -7.00072377e-03],
       [ 1.58186999e+00,  8.45780940e-02, -4.63631293e-02, ...,
         7.31008459e-03,  6.69828780e-03,  4.58389107e-03],
       [ 3.50790455e+00,  3.28823135e-01, -6.74216131e-02, ...,
         1.27775344e-02,  1.10018934e-02, -1.68375103e-02]])

In [11]:
pred_df=pd.DataFrame(all_predicted_ratings_normalize,columns=user_item.columns)
pred_df.head()

movieId    1         2         3         4         5         6         7       \
0       -0.054239  0.045130 -0.004835 -0.019817 -0.011284  0.041373 -0.007822   
1        0.419835  1.406440 -0.188807  0.156658  0.268032  0.414698  0.052172   
2        1.345619  0.266505 -0.011962  0.012278  0.079508  0.090960 -0.122094   
3        1.133455  1.046982  0.141275  0.081841 -0.339675 -1.484659 -0.263096   
4        1.389578  1.466495  0.605557 -0.029647  0.729380 -0.118539 -0.026017   

movieId    8         9         10        ...       161084    161155    161594  \
0       -0.017188  0.012246  0.037670    ...    -0.005258 -0.005453  0.012369   
1        0.044728 -0.020198  2.220256    ...    -0.005909 -0.003974 -0.012555   
2        0.031327 -0.018023  0.141176    ...    -0.002647 -0.002364 -0.010153   
3       -0.169750 -0.021862  1.611664    ...     0.020805  0.000410  0.056040   
4        0.065577 -0.156655  0.307926    ...    -0.007422 -0.011810  0.006644   

movieId    161830    161918    161944    162376    162542    162672    163949  
0       -0.004991 -0.004639 -0.019055  0.021402 -0.006365 -0.006098 -0.004819  
1       -0.003555 -0.002711 -0.071621 -0.016212  0.001047 -0.001468 -0.006577  
2        0.000277 -0.000116 -0.018063 -0.015761  0.010611  0.006792 -0.006357  
3       -0.002817 -0.000767  0.159159  0.087519 -0.030854 -0.021279  0.048529  
4       -0.005159 -0.001249 -0.034658  0.016456  0.001710 -0.004166 -0.001864  

[5 rows x 9066 columns]

In [12]:
def recommend_movies(predictions_df, userID, movies_df, original_ratings_df, num_recommendations=5):
    
    user_row_number = userID - 1 
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False) 
    print(sorted_user_predictions)
    
    user_data = original_ratings_df[original_ratings_df.userId == (userID)]
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'movieId', right_on = 'movieId').
                     sort_values(['rating'], ascending=False)
                 )

    print ('User {0} has already rated {1} movies.'.format(userID, user_full.shape[0]))
    print ('Recommending highest {0} predicted ratings movies not already rated.'.format(num_recommendations))
    
    
    recommendations = (movies_df[~movies_df['movieId'].isin(user_full['movieId'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'movieId',
               right_on = 'movieId').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

In [13]:
already,predictions =recommend_movies(pred_df, 1, movies, data_ratings, 10)
already

movieId
1374     0.274864
2968     0.253016
2105     0.250143
1954     0.214021
2987     0.213012
2193     0.210908
3175     0.201658
3479     0.179425
1293     0.179358
3671     0.178815
1263     0.175830
2947     0.173342
2406     0.166409
1282     0.164725
1957     0.164705
1201     0.163383
1272     0.160849
1287     0.158614
858      0.158072
3108     0.157355
3471     0.157262
2366     0.156408
3168     0.153626
2174     0.151150
2746     0.150880
3740     0.150526
2019     0.149583
3702     0.149574
1136     0.146802
2871     0.146545
           ...   
50872   -0.066193
6377    -0.067082
59315   -0.067768
1732    -0.067965
8981    -0.068671
377     -0.070559
2858    -0.070890
4246    -0.071138
50      -0.072483
46578   -0.073867
8784    -0.074329
4963    -0.079841
3160    -0.079900
597     -0.082640
231     -0.086892
733     -0.087517
3825    -0.088000
7361    -0.089238
1721    -0.090653
6874    -0.094301
4226    -0.095873
5952    -0.096037
539     -0.100434
5418    -0.101309
67

userId  movieId  rating   timestamp  \
4        1     1172     4.0  1260759205   
13       1     2105     4.0  1260759139   
12       1     1953     4.0  1260759191   
8        1     1339     3.5  1260759125   
19       1     3671     3.0  1260759117   
1        1     1029     3.0  1260759179   
2        1     1061     3.0  1260759182   
14       1     2150     3.0  1260759194   
17       1     2455     2.5  1260759113   
0        1       31     2.5  1260759144   
10       1     1371     2.5  1260759135   
9        1     1343     2.0  1260759131   
7        1     1293     2.0  1260759148   
6        1     1287     2.0  1260759187   
5        1     1263     2.0  1260759151   
15       1     2193     2.0  1260759198   
16       1     2294     2.0  1260759108   
3        1     1129     2.0  1260759185   
11       1     1405     1.0  1260759203   
18       1     2968     1.0  1260759200   

                                             title  \
4   Cinema Paradiso (Nuovo cinema Paradiso) (1989)   
13                                     Tron (1982)   
12                   French Connection, The (1971)   
8           Dracula (Bram Stoker's Dracula) (1992)   
19                          Blazing Saddles (1974)   
1                                     Dumbo (1941)   
2                                  Sleepers (1996)   
14                  Gods Must Be Crazy, The (1980)   
17                                 Fly, The (1986)   
0                           Dangerous Minds (1995)   
10            Star Trek: The Motion Picture (1979)   
9                                 Cape Fear (1991)   
7                                    Gandhi (1982)   
6                                   Ben-Hur (1959)   
5                          Deer Hunter, The (1978)   
15                                   Willow (1988)   
16                                     Antz (1998)   
3                      Escape from New York (1981)   
11          Beavis and Butt-Head Do America (1996)   
18                             Time Bandits (1981)   

                                         genres  
4                                         Drama  
13                      Action|Adventure|Sci-Fi  
12                        Action|Crime|Thriller  
8               Fantasy|Horror|Romance|Thriller  
19                               Comedy|Western  
1              Animation|Children|Drama|Musical  
2                                      Thriller  
14                             Adventure|Comedy  
17                 Drama|Horror|Sci-Fi|Thriller  
0                                         Drama  
10                             Adventure|Sci-Fi  
9                                      Thriller  
7                                         Drama  
6                        Action|Adventure|Drama  
5                                     Drama|War  
15                     Action|Adventure|Fantasy  
16  Adventure|Animation|Children|Comedy|Fantasy  
3              Action|Adventure|Sci-Fi|Thriller  
11             Adventure|Animation|Comedy|Crime  
18              Adventure|Comedy|Fantasy|Sci-Fi

In [14]:
predictions

movieId                                              title  \
1103     1374             Star Trek II: The Wrath of Khan (1982)   
1503     1954                                       Rocky (1976)   
2379     2987                    Who Framed Roger Rabbit? (1988)   
2533     3175                                Galaxy Quest (1999)   
2759     3479                                   Ladyhawke (1985)   
2348     2947                                  Goldfinger (1964)   
1899     2406                         Romancing the Stone (1984)   
1030     1282                                    Fantasia (1940)   
1506     1957                            Chariots of Fire (1981)   
953      1201  Good, the Bad and the Ugly, The (Buono, il bru...   

                                                 genres  
1103                   Action|Adventure|Sci-Fi|Thriller  
1503                                              Drama  
2379  Adventure|Animation|Children|Comedy|Crime|Fant...  
2533                            Adventure|Comedy|Sci-Fi  
2759                          Adventure|Fantasy|Romance  
2348                          Action|Adventure|Thriller  
1899                    Action|Adventure|Comedy|Romance  
1030                 Animation|Children|Fantasy|Musical  
1506                                              Drama  
953                            Action|Adventure|Western